control_plane_endpoint: kcl2-m1

join_masters:
  - kcl2-m2
  - kcl2-m3

join_workers:
  - kcl2-w1
  - kcl2-w2
  - kcl2-w3

settings:
  domain_public: codeware.icu
  domain_local: codeware.local

ingress_nginx:
  namespace: ingress-nginx
  enabled: false

metallb:
  namespace: matellb-system
  enabled: false

longhorn:
  namespace: longhorn-system
  enabled: false
  ingress:
    enabled: false
    host_local: "longhorn.{{ settings.domain_local }}"
    host_public: "longhorn.{{ settings.domain_public }}"

cert_manager:
  enabled: false
  namespace: cert-manager
  vars:
    sercret_ref: "letsencrypt-prod"
    email_address: "czyrip@gmail.com"

argocd:
  namespace: argocd
  enabled: false
  ingress:
    enabled: false
    host_local: "argocd.{{ settings.domain_local }}"
    host_public: "argocd.{{ settings.domain_public }}"

metrics:
  namespace: kube-system
  enabled: false

prometheus:
  namespace: monitoring
  enabled: true
  storage:
    size: "2Gi"

grafana:
  namespace: monitoring
  enabled: true
  ingress:
    enabled: true
    host_local: "grafana.{{ settings.domain_local }}"
    host_public: "grafana.{{ settings.domain_public }}"

deploy:
  test_app:
    enabled: false
  argocd_example:
    enabled: false
