control_plane_endpoint: kcl2-m1

join_masters:
  - kcl2-m2
  - kcl2-m3

join_workers:
  - kcl2-w1
  - kcl2-w2
  - kcl2-w3

longhorn:
  namespace: longhorn-system
  enabled: true
  ingress: true
  ingress_host: longhorn.codeware.local

cert_manager:
  enabled: true
  namespace: cert-manager
  vars:
    sercret_ref: "letsencrypt-prod"
    email_address: "czyrip@gmail.com"

argocd:
  namespace: argocd
  enabled: true
  ingress: true
  ingress_host: argocd.codeware.local

metrics:
  namespace: kube-system
  enabled: true
