- name: Create Argocd application namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: argocd-example
    state: present
  ignore_errors: true # @TODO: remove this, add a management host for cluster management

- name: Generate Argocd application from template
  ansible.builtin.template:
    src: root/argocd-example.application.tpl.yml.j2
    dest: /root/argocd-example.application.yml
    mode: '0600'

- name: Apply Argocd application
  kubernetes.core.k8s:
    state: present
    src: /root/argocd-example.application.yml

