---
all:
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_become_user: root
  children:
    kcl2-masters:
      hosts:
        kcl2-m1:
          ansible_host: 192.168.0.121
          ansible_port: 22
          ansible_user: ubuntu
        kcl2-m2:
          ansible_host: 192.168.0.122
          ansible_port: 22
          ansible_user: ubuntu
        kcl2-m3:
          ansible_host: 192.168.0.123
          ansible_port: 22
          ansible_user: ubuntu
    kcl2-workers:
      hosts:      
        kcl2-w1:
          ansible_host: 192.168.0.124
          ansible_port: 22
          ansible_user: ubuntu
        kcl2-w2:
          ansible_host: 192.168.0.125
          ansible_port: 22
          ansible_user: ubuntu
