---
# tasks file for kubernetes-worker
- name: Install common packages
  ansible.builtin.package:
    name:
      - kubernetes-cni
      - kubelet
      - kubeadm
      - open-iscsi
    state: present
