---
# tasks file for common
- name: Update the APT package index
  apt:
    update_cache: yes 
      
- name: Install common packages
  package:
    name:
      - curl
      - vim
      - git
      - wget
      - mc
      - tcpdump
      - gpg
      - net-tools
    state: present
