- name: Output the inventory_hostname
  ansible.builtin.debug:
    msg: "Domain name {{ ansible_facts.domain }} {{ domain_name }}"

- name: Set timezone to Europe/Budapest
  community.general.timezone:
    name: Europe/Budapest

- name: Set domain name
  ansible.builtin.command: "domainname {{ domain_name }}"
  when: ansible_facts.domain != domain_name

- name: Force color
  become: true
  ansible.builtin.lineinfile:
    path: /etc/bash.bashrc
    regexp: "^force_color_prompt=yes$"
    line: "force_color_prompt=yes"
    state: present
    insertafter: EOF
