- name: Output the inventory_hostname
  debug:
    msg: "Domain name {{ ansible_facts.domain }} {{ domain_name }}"

- name: Set timezone to Europe/Budapest
  timezone:
    name: Europe/Budapest

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Set domain name
  command: "domainname {{ domain_name }}"
  when: ansible_facts.domain != domain_name

- name: force color
  become: true
  lineinfile:
    path: /etc/bash.bashrc
    regexp: "^force_color_prompt=yes$"
    line: "force_color_prompt=yes"
    state: present
    insertafter: EOF
