---
    #- name: Create tigera-operator namespace
    #  k8s:
    #    api_version: v1
    #    kind: Namespace
    #    name: tigera-operator
    #    state: present
    #  when: inventory_hostname == control_plane_endpoint      
    #  ignore_errors: true # @TODO: remove this, add a management host for cluster management
    #
    #- name: Install Calico
    #  kubernetes.core.helm_repository:
    #    name: calico
    #    chart_ref: tigera-io/tigera-operator
    #    version: 3.28
    #    namespace: tigera-operator
    #      #values_files:
    #      #  - path/to/values.yaml
    #  when: inventory_hostname == control_plane_endpoint  
    #
- name: Install Calico
  ansible.builtin.shell: "helm upgrade --install calico tigera-io/tigera-operator"
  when: inventory_hostname == control_plane_endpoint
