---
# tasks file for kubernetes-master
- name: Output the inventory_hostname
  ansible.builtin.debug:
    msg: "The initial master is: {{ control_plane_endpoint }}"

- name: Install common packages
  ansible.builtin.package:
    name:
      - kubernetes-cni
      - kubelet
      - kubeadm
    state: present

- name: Generate kubeadm config file from template
  ansible.builtin.template:
    src: kubelet.tpl.yml.j2
    dest: /root/kubelet.yml
    mode: '0600'
  when: inventory_hostname == control_plane_endpoint

- name: Check if the node is already part of the cluster
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf

- name: Init kubernetes initial control plane
  ansible.builtin.shell: "kubeadm init --config /root/kubelet.yml"
  register: kubeadm_output
  ignore_errors: true
  when:
    - inventory_hostname == control_plane_endpoint
    - not kubelet_conf.stat.exists

- name: Display the kubeadm output
  ansible.builtin.debug:
    msg: "The command output is: {{ kubeadm_output.stdout }}"
  when:
    - inventory_hostname == control_plane_endpoint
    - not kubelet_conf.stat.exists

- name: Ensure .kube directory exists
  ansible.builtin.file:
    path: /root/.kube/
    state: directory
    mode: '0600'
  when: inventory_hostname == control_plane_endpoint

- name: Copy admin.conf
  ansible.builtin.command: cp /etc/kubernetes/admin.conf /root/.kube/config
  when: inventory_hostname == control_plane_endpoint

- name: Run kubectl get nodes to test
  ansible.builtin.shell: "kubectl get nodes"
  register: master_nodes
  when: inventory_hostname == control_plane_endpoint

- name: Display the output
  ansible.builtin.debug:
    msg: "The command output is: {{ master_nodes.stdout }}"
  when: inventory_hostname == control_plane_endpoint

- name: Include helm install
  ansible.builtin.import_tasks: install-helm.yml

- name: Include helm repos
  ansible.builtin.import_tasks: add-helm-repos.yml

