- name: Add ingress-nginx repo
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: https://kubernetes.github.io/ingress-nginx
  when: ingress_nginx.enabled | bool

- name: Add metallb repo
  kubernetes.core.helm_repository:
    name: metallb
    repo_url: https://metallb.github.io/metallb
  when: metallb.enabled | bool

- name: Add longhorn repo
  kubernetes.core.helm_repository:
    name: longhorn
    repo_url: https://charts.longhorn.io
  when: longhorn.enabled | bool

- name: Add cert-manager repo
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io
  when: cert_manager.enabled | bool

- name: Add argocd repo
  kubernetes.core.helm_repository:
    name: argocd
    repo_url: https://argoproj.github.io/argo-helm
  when: argocd.enabled | bool

- name: Add bitnami repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
  when: metrics.enabled | bool

- name: Add Prometheus repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts
  when: prometheus.enabled | bool

- name: Add Grafana repo
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts
  when: grafana.enabled | bool
