---
- name: Create nginx-ingres namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: ingress-nginx
    state: present
  ignore_errors: true # @TODO: remove this, add a management host for cluster management

- name: Generate ingress-nginx values config from template
  ansible.builtin.template:
    src: root/ingress-nginx-values.tpl.yml.j2
    dest: /root/ingress-nginx-values.yml
    mode: '0600'

- name: Install ingress-nginx
  ansible.builtin.shell: "helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --values=/root/ingress-nginx-values.yml --namespace=ingress-nginx"
