---
- name: Create Longhorn namespace
  k8s:
    api_version: v1
    kind: Namespace
    name: argocd
    state: present
  ignore_errors: true # @TODO: remove this, add a management host for cluster management

- name: Install Argocd
  ansible.builtin.shell: "helm upgrade --install argocd argocd/argo-cd --namespace argocd"

- name: Generate Argocd ingress from template
  ansible.builtin.template:
    src: root/argocd-ingress.tpl.yml.j2
    dest: /root/longhorn-ingress.yml
    mode: '0600'

- name: Apply Argocd ingress
  kubernetes.core.k8s:
    state: present
    src: /root/argocd-ingress.yml    
