---
- name: Include helm repos
  ansible.builtin.import_tasks: add-helm-repos.yml

- name: Install Ingress-nginx
  ansible.builtin.import_tasks: install-ingress-nginx.yml

- name: Install Metallb
  ansible.builtin.import_tasks: install-metallb.yml

- name: Install Longhorn
  ansible.builtin.import_tasks: install-longhorn.yml
  when: longhorn.enabled | bool

- name: Install Cert-manager
  ansible.builtin.import_tasks: install-cert-manager.yml

- name: Install ArgoCD
  ansible.builtin.import_tasks: install-argocd.yml
  when: argocd.enabled | bool
