---
- name: Include helm repos
  ansible.builtin.import_tasks: add-helm-repos.yml

- name: Install ingress nginx
  ansible.builtin.import_tasks: install-ingress-nginx.yml

- name: Install metallb
  ansible.builtin.import_tasks: install-metallb.yml
