apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: "1.28.0" # Replace with your desired version
controlPlaneEndpoint: "kcl2-m1"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
